### ISSUE TITLE
[Question/Suggestion] Server-side

### ISSUE THREAD

**Issue by diznover** [Galster-dev/BetterSculkSensor#1]
Is this a server-side mod? If not, you can make it server-side, that would be cool.

**Comment by Galster-dev** [comment]
Hello. This mod can (probably) be installed on a separate server. Having it server-side only is not an option because it adds new block, namespace, ids and needs to handle some rendering

**Comment by diznover** [comment]
Thanks for the answer, if you want to make a server-side only mod, you can try to do it with [Polymer](https://github.com/Patbox/polymer), server-side mods is a cool thing, a person can play on a server with advanced redstone mechanics without even setting himself a single mod.
