### ISSUE TITLE
Is the mod suppossed to work beyond 1.19.2?

### ISSUE THREAD

**Issue by saulaxel** [Galster-dev/BetterSculkSensor#3]
Hello, I noticed this mod failed on 1.19.3, but I don't know if this version is unsupported or this is a bug. I see that only 1.19.1 and 1.19.2 are mentioned as supported in the commit 54efb2fcb08c4f0db2484af08db712d265b17cdd, but that could be because the commit dates before 1.19.3 was released since that same commit marks the target minecraft version as "minecraft": ">=1.19", implying that the mod might be intended to work in things beyond the specified 1.19.1 and 1.19.2.

If this is a bug, I'll include some info, but you can ignore it if support for 1.19.3 is not intended. This is the error shown when launching the game:

> The game crashed whilst initializing game
> Error: java.lang.RuntimeException: Could not execute entrypoint stage'main'
> due to errors, provided by 'bettersculksensor'!

This doen't say anything important, but the crash report that I'll attach here actually mentions something about not finding a file named "field_11146". The filename seems to be the same on windows and linux, so it's maybe not a randomly generated file but something more specific.

From the looks of it, fabric loader might have changed something that causes the problem

[crash-2023-03-13_18.23.09-client.txt](https://github.com/Galster-dev/BetterSculkSensor/files/10963157/crash-2023-03-13_18.23.09-client.txt)

**Comment by Galster-dev** [comment]
Hello! Mojang reworked their versioning so 1.19.3 was not just a patch in terms of codebase. It broke most of the mods including this one (I guess, I didn't test it yet), I'll give it a look tomorrow.

**Comment by saulaxel** [comment]
Sure, thank you.

**Comment by Galster-dev** [comment]
v1.2.0 with 1.19.3 support is currently on approval on CurseForge.

**Comment by saulaxel** [comment]
Thanks, I see from the changes made that there were actually quite a few changes to the Minecraft API.
